services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: base_project
      MYSQL_DATABASE: base_project
      MYSQL_USER: base_project
      MYSQL_PASSWORD: base_project
    ports:
      - "3306:3306"
  golang-base-project:
    build: .
    container_name: golang-base-project
    environment:
      - PORT=:80
      - BASE_URL=http://localhost:8080
      - COOKIE_SECRET=
      - DATABASE=mysql
      - DATABASE_NAME=base_project
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=base_project
      - DATABASE_PASSWORD=base_project
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_SENDER=
      - STRICT_TRANSPORT_SECURITY=false
      - REQUESTS_PER_MINUTE=5
    depends_on:
      - db
    ports:
      - "8080:80"

volumes:
  db_data: {}
